{"name": "Проверка авторизации с неверными данными", "status": "passed", "start": 1726094089187, "stop": 1726094089297, "uuid": "b59a9552-c961-45c6-b7ad-8cded2159df9", "historyId": "b6d5415baf69eeca0f75972c0b27cd8f", "testCaseId": "b6d5415baf69eeca0f75972c0b27cd8f", "fullName": "tests.test_authorization.TestAuthorization#test_wrong_data_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorization"}, {"name": "subSuite", "value": "TestAuthorization"}, {"name": "host", "value": "DESKTOP-R9LGN5R"}, {"name": "thread", "value": "68984-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorization"}]}